<a href="https://colab.research.google.com/github/Praneethgajula01/aml-0026/blob/main/aml_numpy_aug11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy

import numpy as np

a=np.array([[7,8,9],[6,7,8]])

print(a.shape)

(2, 3)


In [ ]:
n=np.arange(0,22,3)
n


array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [ ]:
n=n.reshape(2,4)
n


array([[ 0,  3,  6,  9],
       [12, 15, 18, 21]])

In [ ]:
n.resize(2,4)
n

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21]])

In [ ]:
n=np.ones([3,4])
n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
n=np.zeros([4,1000])
n

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
num=np.matrix([[11, 121, 130], [12, 144, 150], [13, 169, 180]])
num

matrix([[ 11, 121, 130],
        [ 12, 144, 150],
        [ 13, 169, 180]])

In [ ]:
type(num)

numpy.matrix

In [ ]:
np.diag(num)

array([ 11, 144, 180])

In [ ]:
#elements above diagnols

np.diag(num,2)

array([130])

In [ ]:
#elements below diagnols

np.diag(num, -2)

array([13])

In [ ]:
n=np.repeat([1,2,3],3)
n

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
n.ndim

1

In [ ]:
n.shape

(9,)

In [ ]:
n.size

9

In [ ]:
p=np.array([1,2,3])
np.vstack([p,2*p])

array([[1, 2, 3],
       [2, 4, 6]])

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])

print(x+y)

[5 7 9]


In [ ]:
print(x*y)

[ 4 10 18]


In [ ]:
print(x@y) #sum of product of elements in two arrays

32


In [ ]:
print(x/y)

[0.25 0.4  0.5 ]


In [ ]:
print(x**2)

[1 4 9]


In [ ]:
x.dot(y)

np.int64(32)

In [ ]:
z=np.array([y, y**2])

In [ ]:
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [ ]:
print(len(z))

2


In [ ]:
z.shape

(2, 3)

In [ ]:
z.T #transpose

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [ ]:
z.T.shape  #shape of transpose matrix z

(3, 2)

In [ ]:

z.dtype

dtype('int64')

In [ ]:
z=z.astype("f")
z.dtype

dtype('float32')

In [ ]:
a=np.array([-4, 5, 1,2,3,4])

a.sum()

np.int64(11)

In [ ]:
print(a.max())

5


In [ ]:
a.min()

np.int64(-4)

In [ ]:
a.mean()

np.float64(1.8333333333333333)

In [ ]:
a.std()

np.float64(2.91070819942883)

In [ ]:
a.argmax()

np.int64(1)

In [ ]:
a.argmin()

np.int64(0)

In [ ]:
import numpy as np

s=np.arange(100)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
s.resize(10,10)
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
s.reshape(10,10)
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
sq=np.arange(6)**2
sq

array([ 0,  1,  4,  9, 16, 25])

In [ ]:
tri=np.arange(6)**3
tri

array([  0,   1,   8,  27,  64, 125])

In [ ]:
tri[2]

np.int64(8)

In [ ]:
tri[3:]

array([ 27,  64, 125])

In [ ]:
tri[1::2]

array([  1,  27, 125])

In [ ]:
tri[2:]

array([  8,  27,  64, 125])

In [ ]:
a=np.arange(90)
a.reshape(9,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [ ]:
r=np.arange(100)
r=r.reshape(10,10)
r[3,4]

np.int64(34)

In [ ]:
r[2, 3:8]

array([23, 24, 25, 26, 27])

In [ ]:
r[:3, :-4]

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [ ]:
res=r[r>49].reshape(5,10)
res

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
r[r>30]=0
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [ ]:
r_copy=r.copy()
print(r)
print(" ")
print(r_copy)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]
 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [ ]:
test=np.random.randint(1,10,(4,3))
print(test)

for i in range(len(test)):
  print(test[i])

[[1 3 2]
 [3 4 7]
 [9 8 2]
 [1 1 4]]
[1 3 2]
[3 4 7]
[9 8 2]
[1 1 4]


In [ ]:
for i, v in enumerate(test):
  print(i, v)

0 [1 3 2]
1 [3 4 7]
2 [9 8 2]
3 [1 1 4]


In [ ]:
test_2=test**2
test_2

array([[ 1,  9,  4],
       [ 9, 16, 49],
       [81, 64,  4],
       [ 1,  1, 16]])

In [ ]:
for i, j in zip(test, test_2):
  print(i+j)

[ 2 12  6]
[12 20 56]
[90 72  6]
[ 2  2 20]


In [ ]:
marks=np.array([[60, 50, 40],
                [12, 90, 65],
                [35, 87, 65]])

#axis=0 for coloumns operation
#axis=1 for row wise operation

student_total=np.sum(marks, axis=1)
print("total of each student:", student_total)

student_h_marks=np.max(marks, axis=1)
print("student highest marks:", student_h_marks)



total of each student: [150 167 187]
student highest marks: [60 90 87]


In [ ]:
#Q1

a=np.ones((2, 2))
for i, j in enumerate(a):
  a[i]=7
a

array([[7., 7.],
       [7., 7.]])

In [ ]:
#Q2

r=np.random.rand(2,2)
r

array([[0.52282625, 0.11173004],
       [0.64668255, 0.87706345]])

In [ ]:
#Q3

p=np.arange(10,51)
print("the array: ", p)
print(len(p))
print(p.shape)
print(p.ndim)
print(p.dtype)

the array:  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
41
(41,)
1
int64


In [ ]:
#Q4

a=np.zeros(10)
print(a)
a.ndim
print("-------")

#3x3 array containing all 1

a=np.ones((3,3))
print(a)

print("-------")
#4x4 identity matrix

i=np.identity(4)
print(i)

ident=np.diag(i)
assert np.sum(ident)==4

print("-------")

#array btw 5 to 50, with step size of 5

arr=np.arange(5,50, 5)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
-------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-------
[ 5 10 15 20 25 30 35 40 45]


In [ ]:
a=np.arange(1,25)
print(a)


a46=a.reshape(4,6)
print(a46.shape)
print(a46.ndim)

a64=a.reshape(6,4)
print(a64.shape)
print(a64.ndim)

a234=a.reshape(2,3,4)
print(a234.shape)
print(a234.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(4, 6)
2
(6, 4)
2
(2, 3, 4)
3


In [ ]:
#Q6

marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

print(marks[0])
print(marks[-1])
print(marks[2])
print(marks[:4])
print(marks[-3:])

78
81
92
[78 85 92 67]
[73 95 81]


In [ ]:
#Q7

a=np.arange(10,51, 10)
b=np.arange(5,26, 5)
print("a=",a, "b=",b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

a= [10 20 30 40 50] b= [ 5 10 15 20 25]
[15 30 45 60 75]
[ 5 10 15 20 25]
[  50  200  450  800 1250]
[2. 2. 2. 2. 2.]
[ 100  400  900 1600 2500]


In [ ]:
#Q8

salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

print(salary)

print(np.sum(salary))

n=len(salary)
avg=np.sum(salary)/n

print("avg is:", avg)

print(np.max(salary))
print(np.min(salary))

#median - np.median()

print(np.median(salary))

#standard deviation - np.std()

print(np.std(salary ))

[25000 32000 28000 45000 50000 38000 42000 30000]
290000
avg is: 36250.0
50000
25000
35000.0
8317.902379807063


In [ ]:
#Q9

marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

m=marks[marks>75]
print("marks greater than 75:", m)
m=marks[(marks>50)&(marks<80)]
print("marks>50 and marks < 80:", m)
print("student scores <50:", len(marks[marks<50]))

marks greater than 75: [78 89 90 76 84]
marks>50 and marks < 80: [78 67 55 76]
student scores <50: 3


In [ ]:
m=marks[marks>=60]
n=len(marks)
res=len(m)/n
print("percent of scores >=60:",res*100)

percent of scores >=60: 60.0


In [ ]:
import numpy as np
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

s_marks=np.sum(marks, axis=1)
print(s_marks)
avg_score=np.mean(marks, axis=1)
print("Average marks of each student", avg_score)
avg_score=np.mean(marks, axis=0)
print("Average marks in each subject", avg_score)
print("student with highest marks:", np.argmax(s_marks))
print("highest mark in each subject:", np.max(marks, axis=0))

[245 207 265 173]
Average marks of each student [81.66666667 69.         88.33333333 57.66666667]
Average marks in each subject [72.   74.25 76.25]
student with highest marks: 2
highest mark in each subject: [88 92 90]


In [ ]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A+B)

print(A*B)

print(A.T)

print(A@B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]
[[19 22]
 [43 50]]


In [ ]:
temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])


print("the mean of temp is:", temperature.mean())
print("the max temp is:", np.max(temperature), "the min temp is:", np.min(temperature))

print("the no of days above avg:", len(temperature[temperature>temperature.mean()]))

print("the no of days >34:", len(temperature[temperature>34]))
print("the std:", temperature.std())

the mean of temp is: 33.142857142857146
the max temp is: 37 the min temp is: 29
the no of days above avg: 6
the no of days >34: 5
the std: 2.356060357495806


In [ ]:
sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

print("total annual sales:", np.sum(sales))

print("avg:", np.average(sales))

print("highest sales month:", np.argmax(sales)+1)
print("least sales month:", np.argmin(sales)+1)

print(">20k:", len(sales[sales>20000]))

print("% increase from jan to dec:", ((sales[-1]-sales[0])/sales[0])*100)



total annual sales: 240000
avg: 20000.0
highest sales month: 12
least sales month: 1
>20k: 6
% increase from jan to dec: 133.33333333333331


In [ ]:
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])




In [ ]:
#generate 20 random integers 1 to 100

n=np.random.randint(1, 100, 20)
n

array([41, 71, 43, 98, 55, 37, 78, 93, 65, 50, 43, 60, 26, 11, 89, 92, 76,
       91, 51, 15])

In [ ]:
n1=n[n%2==0]
n1

array([98, 78, 50, 60, 26, 92, 76])

In [ ]:
#n[n<50]=0
n


array([41, 71, 43, 98, 55, 37, 78, 93, 65, 50, 43, 60, 26, 11, 89, 92, 76,
       91, 51, 15])

In [ ]:
print(np.sort(n))
print(np.sort(n)[::-1])

[11 15 26 37 41 43 43 50 51 55 60 65 71 76 78 89 91 92 93 98]
[98 93 92 91 89 78 76 71 65 60 55 51 50 43 43 41 37 26 15 11]


In [ ]:
n3=np.unique(n, return_counts=True)
print(n3)

(array([11, 15, 26, 37, 41, 43, 50, 51, 55, 60, 65, 71, 76, 78, 89, 91, 92,
       93, 98]), array([1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))


In [ ]:
print(np.unique(n))

[11 15 26 37 41 43 50 51 55 60 65 71 76 78 89 91 92 93 98]


In [ ]:
n=np.random.randint(1, 100, [5,5])
n

array([[75, 15, 13, 17, 32],
       [11, 82, 32,  2,  3],
       [ 1, 14, 98, 25, 23],
       [26, 81, 50, 45, 19],
       [72, 63, 48,  9, 88]])

In [ ]:
print(np.mean(n, axis=1)) #row wise mean
print(np.mean(n, axis=0)) #column wise mean

[30.4 26.  32.2 44.2 56. ]
[37.  51.  48.2 19.6 33. ]
